### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by TeamCoda-sys** [CreeperGreg95/Programmes#1]
Salut, comment ta fais pour ta licence ? ta demandé les droit ?

**Comment by CreeperGreg95** [comment]
Nan , je dis juste que ça vient des liens officiaux et c'est tout !$

:)


Juste, Le compte Discord Grégory#7801 n'existe plus (je n'y ai plus l'accès), donc mon nouveau compté c'est CreeperGreg95#4288 (je suis déjà sur ton serveur Discord (Team Coda))

Bonne Soirée

CreeperGreg95

© 2021 L'Univers des Jeux Vidéos, Inc.                                                             Tout droits réservés

**Comment by CreeperGreg95** [comment]
As-tu d'autres questions à me poser avant que ce commentaire se ferme ?

Je le ferme le 03 juillet à 21h
